import { useEffect, useState } from "react";
import { api } from "../api";
import { useJobActivity } from "./JobActivity";
import { JobView } from "./JobView";
import type { ExperimentDefinition, ExperimentSchema, Job, ParameterLayout, ParameterValues, SchemaField } from "../types/api";
import { ParameterForm } from "./MxYOptimalControlFrequency/ParameterForm";
import { sameParameterLayout, validatedParameterLayout } from "../pages/experimentHelpers";

type StaticRunSummary = { timestamp: string; run_tag: string; completion_status: string; analysis: Record<string, unknown>; artifacts: Record<string, string> };
type Props = { experimentId: string; definition: ExperimentDefinition; fields: SchemaField[]; layout: ParameterLayout; layoutDirty: boolean; onLayoutChange: (next: ParameterLayout) => void; onLayoutSaved: (next: ParameterLayout) => void; values: ParameterValues; setValues: (next: ParameterValues) => void; job: Job | undefined; setJob: (next: Job | undefined) => void; prefill: ParameterValues | null; clearPrefill: () => void };

export function StaticSensitivityDashboard({ experimentId, definition, fields, layout, layoutDirty, onLayoutChange, onLayoutSaved, values, setValues, job, setJob, prefill, clearPrefill }: Props) {
  const { hardwareBusy, activeJobs } = useJobActivity();
  const [starting, setStarting] = useState(false); const [saving, setSaving] = useState(false); const [preflight, setPreflight] = useState<{ ok: boolean; errors: string[] }>(); const [status, setStatus] = useState<{ ok: boolean; message: string }>(); const [error, setError] = useState("");
  const jobActive = Boolean(job && ["queued", "running"].includes(job.status)); const blocked = hardwareBusy || activeJobs.some((item) => item.kind === `experiment:${experimentId}` && ["queued", "running"].includes(item.status));
  useEffect(() => { if (!prefill) return; setValues({ ...values, ...prefill }); clearPrefill(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prefill]);
  const update = (field: SchemaField, value: ParameterValues[string]) => setValues({ ...values, [field.name]: value });
  const check = async () => { setError(""); try { setPreflight(await api<{ ok: boolean; errors: string[] }>(`/api/experiments/${experimentId}/preflight`, { method: "POST", body: JSON.stringify({ parameters: values }) })); } catch (reason) { setError(String(reason)); } };
  const run = async () => { setError(""); setPreflight(undefined); setStarting(true); try { const result = await api<{ ok: boolean; errors: string[] }>(`/api/experiments/${experimentId}/preflight`, { method: "POST", body: JSON.stringify({ parameters: values }) }); setPreflight(result); if (result.ok) setJob(await api<Job>(`/api/experiments/${experimentId}/runs`, { method: "POST", body: JSON.stringify({ parameters: values }) })); } catch (reason) { setError(String(reason)); } finally { setStarting(false); } };
  const save = async () => { setSaving(true); setStatus(undefined); try { const result = await api<{ message: string; schema: ExperimentSchema }>(`/api/experiments/${experimentId}/defaults`, { method: "PUT", body: JSON.stringify({ parameters: values, parameter_layout: layout }) }); const persisted = result.schema.parameter_layout_saved ? validatedParameterLayout(result.schema.fields, result.schema.parameter_layout) : undefined; if (!persisted || !sameParameterLayout(persisted, layout)) throw new Error("后端未确认参数布局已保存"); onLayoutSaved(persisted); setStatus({ ok: true, message: result.message }); } catch (reason) { setStatus({ ok: false, message: String(reason) }); } finally { setSaving(false); } };
  return <div className="zaw-dashboard"><section className="zaw-panel zaw-panel-params"><div className="zaw-panel-head"><small>PARAMETERS</small><h2>实验参数</h2></div><ParameterForm fields={fields} layout={layout} values={values} onChange={update} onLayoutChange={onLayoutChange} onMoveNotice={() => undefined} disabled={jobActive || starting} />{layoutDirty && <p className="zaw-layout-dirty" role="status">布局有未保存修改</p>}<button className="zaw-secondary" disabled={saving || jobActive} onClick={() => void save()}>{saving ? "保存中…" : "保存参数与布局"}</button>{status && <div className={`alert ${status.ok ? "success" : "error"}`}>{status.message}</div>}</section><section className="zaw-panel zaw-panel-control"><div className="zaw-panel-head"><small>CONTROL</small><h2>控制与状态</h2></div><div className="zaw-control-buttons"><button className="zaw-secondary" disabled={starting || jobActive || blocked} onClick={() => void check()}>仅预检</button><button className="zaw-primary" disabled={starting || jobActive || blocked} onClick={() => void run()}>{jobActive ? "实验运行中" : starting ? "正在启动…" : "预检并运行实验"}</button></div>{preflight && <div className={`alert ${preflight.ok ? "success" : "error"}`}>{preflight.ok ? "参数预检通过，可以启动实验。" : preflight.errors.join("；")}</div>}{blocked && !jobActive && <div className="alert">其他硬件任务正在运行，等待其完成后才能启动本实验。</div>}{error && <div className="alert error">{error}</div>}<div className="zaw-control-meta"><div><small>执行模式</small><span>{definition.execution_mode}</span></div><div><small>所需设备</small><span>{definition.required_devices.join(" · ")}</span></div><div><small>采集程序</small><span>{definition.acquisition_program}</span></div></div><JobView job={job} onUpdate={setJob} /></section><section className="zaw-panel zaw-panel-result"><div className="zaw-panel-head"><small>LATEST</small><h2>最近一次结果</h2></div><LatestPreview job={job} busy={jobActive} /></section></div>;
}

function LatestPreview({ job, busy }: { job: Job | undefined; busy: boolean }) { const [summary, setSummary] = useState<StaticRunSummary>(); useEffect(() => { const result = job?.result as { run_dir?: unknown } | undefined; const runDir = typeof result?.run_dir === "string" ? result.run_dir : ""; const runId = runDir.split(/[\\/]/).pop() ?? ""; if (!runId) return; api<StaticRunSummary>(`/api/experiments/static-sensitivity/runs/${encodeURIComponent(runId)}/summary`).then(setSummary).catch(() => undefined); }, [job?.id, job?.status]); if (!summary) return <p className="zaw-empty">{busy ? "正在采集，运行结束后会展示结果。" : "尚无运行结果，启动一次实验后这里会展示灵敏度分析。"}</p>; const analysis = summary.analysis; return <div className="zaw-latest"><div className="zaw-metrics-grid"><div className="zaw-metric"><small>完成状态</small><span className="zaw-metric-value">{summary.completion_status}</span></div><div className="zaw-metric"><small>拟合状态</small><span className="zaw-metric-value">{analysis.fit_valid ? "有效" : "无效"}</span></div><div className="zaw-metric"><small>最佳 GS200 量程</small><span className="zaw-metric-value">{String(analysis.best_range_label ?? "—")}</span></div><div className="zaw-metric"><small>平坦段灵敏度</small><span className="zaw-metric-value">{formatNumber(analysis.sensitivity_flat_fT_per_sqrt_Hz)} fT/√Hz</span></div></div><p className="zaw-latest-meta">{summary.timestamp} · {summary.run_tag}</p>{summary.artifacts.full_analysiswithoutpump_png && <figure className="zaw-figure"><figcaption>色散、噪声与灵敏度结果</figcaption><img src={summary.artifacts.full_analysiswithoutpump_png} alt="静磁场灵敏度分析结果" loading="lazy" /></figure>}</div>; }
const formatNumber = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value.toString() : "—";
