/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Control Targets */
        get: operations["control_targets_api_control_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Control Target */
        post: operations["refresh_control_target_api_control_targets__mapping_key__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh All Control Targets */
        post: operations["refresh_all_control_targets_api_control_targets_refresh_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/generator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Generator */
        put: operations["update_control_generator_api_control_targets__mapping_key__generator_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/current-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Current Source */
        put: operations["update_control_current_source_api_control_targets__mapping_key__current_source_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/laser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Laser */
        put: operations["update_control_laser_api_control_targets__mapping_key__laser_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/emission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Emission */
        put: operations["update_control_emission_api_control_targets__mapping_key__emission_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Scope */
        put: operations["update_control_scope_api_control_targets__mapping_key__scope_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-targets/{mapping_key}/tec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Control Tec */
        put: operations["update_control_tec_api_control_targets__mapping_key__tec_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device-library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Library */
        get: operations["device_library_api_device_library_get"];
        /** Update Device Library */
        put: operations["update_device_library_api_device_library_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device-library/discover-visa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Device Library */
        post: operations["discover_device_library_api_device_library_discover_visa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/physical-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Physical Mappings */
        get: operations["physical_mappings_api_physical_mappings_get"];
        /** Update Physical Mappings */
        put: operations["update_physical_mappings_api_physical_mappings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Device */
        post: operations["refresh_device_api_devices__device_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/channels/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Channel */
        put: operations["update_channel_api_devices__device_id__channels__channel__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Scope */
        put: operations["update_scope_api_devices__device_id__scope_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/current-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Current Source */
        put: operations["update_current_source_api_devices__device_id__current_source_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/laser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Laser */
        put: operations["update_laser_api_devices__device_id__laser_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/emission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Laser Emission */
        put: operations["update_laser_emission_api_devices__device_id__emission_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clocks/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Clocks */
        post: operations["sync_clocks_api_clocks_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/demod0-phase-calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phase Calibration */
        post: operations["phase_calibration_api_tools_demod0_phase_calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/keithley-waveform-convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keithley Waveform Convert
         * @description ������ӿڣ����� 6221 ���Ⲩ��궨�ı�������������磬������Ӳ����
         */
        post: operations["keithley_waveform_convert_api_tools_keithley_waveform_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiment-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Tags */
        get: operations["experiment_tags_api_experiment_tags_get"];
        put?: never;
        /** Create Experiment Tag */
        post: operations["create_experiment_tag_api_experiment_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiment-tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Experiment Tag */
        put: operations["update_experiment_tag_api_experiment_tags__tag_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment */
        get: operations["experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Experiment Assignment */
        put: operations["update_experiment_assignment_api_experiments__experiment_id__tag_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Experiment Description */
        put: operations["update_experiment_description_api_experiments__experiment_id__description_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Experiment Metadata */
        put: operations["update_experiment_metadata_api_experiments__experiment_id__metadata_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Schema */
        get: operations["experiment_schema_api_experiments__experiment_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Experiment Defaults */
        put: operations["save_experiment_defaults_api_experiments__experiment_id__defaults_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Experiment Preflight */
        post: operations["experiment_preflight_api_experiments__experiment_id__preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/derive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Experiment Derive */
        post: operations["experiment_derive_api_experiments__experiment_id__derive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Experiment Run */
        post: operations["experiment_run_api_experiments__experiment_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Run */
        post: operations["analyze_run_api_runs__run_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{experiment_id}/{run_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_api_runs__experiment_id___run_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frontend */
        get: operations["frontend__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisBody */
        AnalysisBody: {
            /** Experiment Id */
            experiment_id: string;
        };
        /** BurstSettings */
        BurstSettings: {
            /** Enabled */
            enabled?: boolean | null;
            /** Mode */
            mode?: string | null;
            /** Ncycles */
            ncycles?: number | string | null;
            /** Phase */
            phase?: number | null;
            /** Period */
            period?: number | null;
            /** Delay */
            delay?: number | null;
            /** Trigger Source */
            trigger_source?: string | null;
            /** Trigger Slope */
            trigger_slope?: string | null;
        };
        /** BurstSnapshot */
        BurstSnapshot: {
            /** Enabled */
            enabled: boolean;
            /** Mode */
            mode: string | null;
            /** Ncycles */
            ncycles: number | string | null;
            /** Phase */
            phase: number | null;
            /** Period */
            period: number | null;
            /** Delay */
            delay: number | null;
            /** Trigger Source */
            trigger_source: string | null;
            /** Trigger Slope */
            trigger_slope: string | null;
        };
        /** ControlCurrentSourceBody */
        ControlCurrentSourceBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["CurrentSourceSettings"];
        };
        /** ControlEmissionBody */
        ControlEmissionBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["LaserEmissionSettings"];
        };
        /** ControlEndpoint */
        ControlEndpoint: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "channel" | "demod" | "laser_channel";
            /** Index */
            index: number;
        };
        /** ControlGeneratorBody */
        ControlGeneratorBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["GeneratorChannelSettings"];
        };
        /** ControlLaserBody */
        ControlLaserBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["LaserSettings"];
        };
        /** ControlRevisionBody */
        ControlRevisionBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
        };
        /** ControlScopeBody */
        ControlScopeBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["ScopeSettings"];
        };
        /** ControlTarget */
        ControlTarget: {
            /** Mapping Key */
            mapping_key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "generator" | "current_source" | "laser" | "scope" | "tec" | "hf2";
            /** Device Id */
            device_id: string;
            /** Device Label */
            device_label: string;
            /** Model */
            model: string;
            /** Short Resource */
            short_resource: string;
            endpoint: components["schemas"]["ControlEndpoint"] | null;
            /** Shared Mapping Keys */
            shared_mapping_keys: string[];
            /** Safety */
            safety: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Read Only */
            read_only: boolean;
        };
        /** ControlTargetBulkItem */
        ControlTargetBulkItem: {
            target: components["schemas"]["ControlTarget"];
            /** Snapshot */
            snapshot?: (components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"]) | null;
            /** Read At */
            read_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ControlTargetBulkResponse */
        ControlTargetBulkResponse: {
            /** Results */
            results: components["schemas"]["ControlTargetBulkItem"][];
        };
        /** ControlTargetCatalog */
        ControlTargetCatalog: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            /** Targets */
            targets: components["schemas"]["ControlTarget"][];
        };
        /** ControlTargetResponse */
        ControlTargetResponse: {
            target: components["schemas"]["ControlTarget"];
            /** Snapshot */
            snapshot: components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
            /** Read At */
            read_at: string;
        };
        /** ControlTecBody */
        ControlTecBody: {
            /** Device Library Revision */
            device_library_revision: string;
            /** Physical Mapping Revision */
            physical_mapping_revision: string;
            settings: components["schemas"]["TecSettings"];
        };
        /** CurrentSourceDeviceSnapshot */
        CurrentSourceDeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GS200";
            /** Idn */
            idn: string;
            /** Mapping Key */
            mapping_key: string;
            /** Source Function */
            source_function: string;
            /** Output */
            output: boolean;
            /** Current Ma */
            current_ma: number | null;
            /** Current Range Ma */
            current_range_ma: number | null;
            /** Voltage Limit V */
            voltage_limit_v: number;
            /** Current Limit Ma */
            current_limit_ma: number;
            /** Min Current Ma */
            min_current_ma: number;
            /** Max Current Ma */
            max_current_ma: number;
        };
        /** CurrentSourceSettings */
        CurrentSourceSettings: {
            /** Current Ma */
            current_ma?: number | null;
            /** Output */
            output?: boolean | null;
            /**
             * Confirm Output Enable
             * @default false
             */
            confirm_output_enable: boolean;
            /** Current Range Ma */
            current_range_ma?: number | null;
            /** Autorange */
            autorange?: boolean | null;
            /** Compliance V */
            compliance_v?: number | null;
            /** Analog Filter */
            analog_filter?: boolean | null;
            /** Output Response */
            output_response?: ("FAST" | "SLOW") | null;
            waveform?: components["schemas"]["Keithley6221WaveformSettings"] | null;
        };
        /** CurrentSourceSettingsBody */
        CurrentSourceSettingsBody: {
            settings: components["schemas"]["CurrentSourceSettings"];
        };
        /** DeviceChannel */
        DeviceChannel: {
            /** Number */
            number: number;
            /** Label */
            label: string;
            /** Mapping Key */
            mapping_key: string;
            /** Mapping Keys */
            mapping_keys?: string[];
            /** Read Only */
            read_only: boolean;
        };
        /** DeviceLibraryBody */
        DeviceLibraryBody: {
            /** Base Revision */
            base_revision: string;
            /** Devices */
            devices: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** DeviceSummary */
        DeviceSummary: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Type
             * @enum {string}
             */
            type: "DG4000" | "DG900" | "GS200" | "6221" | "DLC_PRO" | "SDS";
            /** Channels */
            channels: components["schemas"]["DeviceChannel"][];
        };
        /** ExperimentBody */
        ExperimentBody: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** ExperimentDefaultsBody */
        ExperimentDefaultsBody: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            parameter_layout?: components["schemas"]["ParameterLayoutBody"] | null;
        };
        /** ExperimentDescriptionBody */
        ExperimentDescriptionBody: {
            /** Description */
            description: string;
        };
        /** ExperimentMetadataBody */
        ExperimentMetadataBody: {
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** GeneratorChannelSettings */
        GeneratorChannelSettings: {
            /** Mapping Key */
            mapping_key?: string | null;
            /** Output */
            output?: boolean | null;
            /** Shape */
            shape?: string | null;
            /** Frequency */
            frequency?: number | null;
            /** Amplitude */
            amplitude?: number | null;
            /** Offset */
            offset?: number | null;
            /** Phase */
            phase?: number | null;
            /** Voltage Unit */
            voltage_unit?: string | null;
            /** Load */
            load?: number | string | null;
            /** Square Duty */
            square_duty?: number | null;
            /** Ramp Symmetry */
            ramp_symmetry?: number | null;
            /** Pulse Width */
            pulse_width?: number | null;
            /** Pulse Delay */
            pulse_delay?: number | null;
            /** Target Mode */
            target_mode?: ("mod" | "burst") | null;
            mod?: components["schemas"]["ModulationSettings"] | null;
            burst?: components["schemas"]["BurstSettings"] | null;
        };
        /** GeneratorChannelSettingsBody */
        GeneratorChannelSettingsBody: {
            settings: components["schemas"]["GeneratorChannelSettings"];
        };
        /** GeneratorChannelSnapshot */
        GeneratorChannelSnapshot: {
            /** Number */
            number: number;
            /** Mapping Key */
            mapping_key: string;
            /** Mapping Keys */
            mapping_keys?: string[];
            /** Label */
            label: string;
            /** Read Only */
            read_only: boolean;
            /** Output */
            output: boolean;
            /** Shape */
            shape: string;
            /** Frequency */
            frequency: number | null;
            /** Amplitude */
            amplitude: number | null;
            /** Offset */
            offset: number | null;
            /** Phase */
            phase: number | null;
            /** Voltage Unit */
            voltage_unit: string | null;
            /** Load */
            load: number | string | null;
            /** Square Duty */
            square_duty: number | null;
            /** Ramp Symmetry */
            ramp_symmetry: number | null;
            /** Pulse Width */
            pulse_width: number | null;
            /** Pulse Delay */
            pulse_delay: number | null;
            mod: components["schemas"]["ModulationSnapshot"];
            burst: components["schemas"]["BurstSnapshot"];
            /** Readback Errors */
            readback_errors: components["schemas"]["ReadbackError"][];
        };
        /** GeneratorDeviceSnapshot */
        GeneratorDeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DG4000" | "DG900";
            /** Idn */
            idn: string;
            /** Reference Clock */
            reference_clock: string;
            /** Channels */
            channels: components["schemas"]["GeneratorChannelSnapshot"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hf2DeviceSnapshot */
        Hf2DeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HF2";
            /** Demod Idx */
            demod_idx: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** R */
            r: number;
            /** Phase */
            phase: number;
            /** Frequency */
            frequency: number;
            /** Enabled */
            enabled: boolean;
            /** Sample Rate */
            sample_rate: number;
            /** Time Constant */
            time_constant: number;
            /** Order */
            order: number;
            /** Harmonic */
            harmonic: number;
            /** Phase Shift */
            phase_shift: number;
        };
        JsonValue: unknown;
        /** Keithley6221DeviceSnapshot */
        Keithley6221DeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "6221";
            /** Idn */
            idn: string;
            /** Mapping Key */
            mapping_key: string;
            /** Output */
            output: boolean;
            /** Current Ma */
            current_ma: number;
            /** Current Range Ma */
            current_range_ma: number;
            /** Autorange */
            autorange: boolean;
            /** Compliance V */
            compliance_v: number;
            /** Analog Filter */
            analog_filter: boolean;
            /**
             * Output Response
             * @enum {string}
             */
            output_response: "FAST" | "SLOW";
            /** Min Current Ma */
            min_current_ma: number;
            /** Max Current Ma */
            max_current_ma: number;
            waveform: components["schemas"]["Keithley6221WaveformSnapshot"];
        };
        /** Keithley6221WaveformSettings */
        Keithley6221WaveformSettings: {
            /**
             * Action
             * @enum {string}
             */
            action: "configure" | "configure_and_start" | "abort";
            /** Shape */
            shape?: ("SIN" | "SQU" | "RAMP" | "ARB") | null;
            /** Frequency Hz */
            frequency_hz?: number | null;
            /** Amplitude Peak Ma */
            amplitude_peak_ma?: number | null;
            /** Offset Ma */
            offset_ma?: number | null;
            /** Duty Cycle Percent */
            duty_cycle_percent?: number | null;
            /** Ranging */
            ranging?: ("BEST" | "FIXED") | null;
            /** Duration Mode */
            duration_mode?: ("TIME" | "CYCLES" | "INFINITE") | null;
            /** Duration Value */
            duration_value?: number | null;
            /** Arbitrary Points */
            arbitrary_points?: number[] | null;
            /**
             * Confirm Start
             * @default false
             */
            confirm_start: boolean;
        };
        /** Keithley6221WaveformSnapshot */
        Keithley6221WaveformSnapshot: {
            /**
             * Shape
             * @enum {string}
             */
            shape: "SIN" | "SQU" | "RAMP" | "ARB";
            /** Frequency Hz */
            frequency_hz: number;
            /** Amplitude Peak Ma */
            amplitude_peak_ma: number;
            /** Offset Ma */
            offset_ma: number;
            /** Duty Cycle Percent */
            duty_cycle_percent: number;
            /**
             * Ranging
             * @enum {string}
             */
            ranging: "BEST" | "FIXED";
            /**
             * Duration Mode
             * @enum {string}
             */
            duration_mode: "TIME" | "CYCLES" | "INFINITE" | "MIXED";
            /** Duration Value */
            duration_value: number | null;
            /** Duration Time S */
            duration_time_s: number | "INF";
            /** Duration Cycles */
            duration_cycles: number | "INF";
            /** Arbitrary Point Count */
            arbitrary_point_count: number;
        };
        /** KeithleyWaveformConvertBody */
        KeithleyWaveformConvertBody: {
            /**
             * Arbitrary Text
             * @default
             */
            arbitrary_text: string;
            /** Calibration Text */
            calibration_text?: string | null;
        };
        /** LaserDeviceSnapshot */
        LaserDeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DLC_PRO";
            /** Controller Serial */
            controller_serial: string;
            /** System Type */
            system_type: string;
            /** System Label */
            system_label: string;
            /** Firmware Version */
            firmware_version: string;
            /** System Health Code */
            system_health_code: number;
            /** System Health */
            system_health: string;
            /** Interlock Open */
            interlock_open: boolean;
            /** Front Key Locked */
            front_key_locked: boolean;
            /** Emission */
            emission: boolean;
            /** Laser Type */
            laser_type: string;
            /** Laser Product Name */
            laser_product_name: string;
            /** Laser Enabled */
            laser_enabled: boolean;
            /** Laser Health Code */
            laser_health_code: number;
            /** Laser Health */
            laser_health: string;
            /** Laser Emission */
            laser_emission: boolean;
            /** Laser Head Model */
            laser_head_model: string;
            /** Laser Head Serial */
            laser_head_serial: string;
            /** Current Set Ma */
            current_set_ma: number;
            /** Current Actual Ma */
            current_actual_ma: number;
            /** Current Clip Ma */
            current_clip_ma: number;
            /** Current Clip Limit Ma */
            current_clip_limit_ma: number;
            /** Min Current Ma */
            min_current_ma: number;
            /** Max Current Ma */
            max_current_ma: number;
            /** Temperature Set C */
            temperature_set_c: number;
            /** Temperature Actual C */
            temperature_actual_c: number;
            /** Min Temperature C */
            min_temperature_c: number;
            /** Max Temperature C */
            max_temperature_c: number;
            /** Pzt Voltage V */
            pzt_voltage_v: number;
            /** Pzt Actual V */
            pzt_actual_v: number;
            /** Min Pzt Voltage V */
            min_pzt_voltage_v: number;
            /** Max Pzt Voltage V */
            max_pzt_voltage_v: number;
            /** Scan Amplitude Vpp */
            scan_amplitude_vpp: number;
            /** Min Scan Amplitude Vpp */
            min_scan_amplitude_vpp: number;
            /** Max Scan Amplitude Vpp */
            max_scan_amplitude_vpp: number;
            /** Scan Frequency Hz */
            scan_frequency_hz: number;
            /** Scan Enabled */
            scan_enabled: boolean;
            /** Scan Unit */
            scan_unit: string;
            /** Scan Output Channel */
            scan_output_channel: number;
            /** Remote Emission Control Enabled */
            remote_emission_control_enabled: boolean;
            /** Safety Keys */
            safety_keys: {
                [key: string]: string;
            };
            /** State Known */
            state_known: boolean;
        };
        /** LaserEmissionSettings */
        LaserEmissionSettings: {
            /** Enabled */
            enabled: boolean;
            /**
             * Safety Acknowledged
             * @default false
             */
            safety_acknowledged: boolean;
            /**
             * Confirm Emission Enable
             * @default false
             */
            confirm_emission_enable: boolean;
            /** Confirmation Text */
            confirmation_text?: string | null;
        };
        /** LaserEmissionSettingsBody */
        LaserEmissionSettingsBody: {
            settings: components["schemas"]["LaserEmissionSettings"];
        };
        /** LaserSettings */
        LaserSettings: {
            /** Current Set Ma */
            current_set_ma?: number | null;
            /** Temperature Set C */
            temperature_set_c?: number | null;
            /** Pzt Voltage V */
            pzt_voltage_v?: number | null;
            /** Scan Amplitude Vpp */
            scan_amplitude_vpp?: number | null;
            /** Scan Enabled */
            scan_enabled?: boolean | null;
        };
        /** LaserSettingsBody */
        LaserSettingsBody: {
            settings: components["schemas"]["LaserSettings"];
        };
        /** ModulationSettings */
        ModulationSettings: {
            /** Enabled */
            enabled?: boolean | null;
            /** Type */
            type?: ("AM" | "FM" | "PM" | "FSKey" | "PWM") | null;
            /** Source */
            source?: string | null;
            /** Internal Frequency */
            internal_frequency?: number | null;
            /** Internal Function */
            internal_function?: string | null;
            /** Am Depth */
            am_depth?: number | null;
            /** Fm Deviation */
            fm_deviation?: number | null;
            /** Pm Deviation */
            pm_deviation?: number | null;
            /** Fsk Frequency */
            fsk_frequency?: number | null;
            /** Fsk Rate */
            fsk_rate?: number | null;
            /** Fsk Polarity */
            fsk_polarity?: string | null;
            /** Pwm Duty Deviation */
            pwm_duty_deviation?: number | null;
        };
        /** ModulationSnapshot */
        ModulationSnapshot: {
            /** Enabled */
            enabled: boolean;
            /** Type */
            type: ("AM" | "FM" | "PM" | "FSKey" | "PWM") | null;
            /** Source */
            source: string | null;
            /** Internal Frequency */
            internal_frequency: number | null;
            /** Internal Function */
            internal_function: string | null;
            /** Am Depth */
            am_depth: number | null;
            /** Fm Deviation */
            fm_deviation: number | null;
            /** Pm Deviation */
            pm_deviation: number | null;
            /** Fsk Frequency */
            fsk_frequency: number | null;
            /** Fsk Rate */
            fsk_rate: number | null;
            /** Fsk Polarity */
            fsk_polarity: string | null;
            /** Pwm Duty Deviation */
            pwm_duty_deviation: number | null;
        };
        /** ParameterLayoutBody */
        ParameterLayoutBody: {
            /** Basic */
            basic: string[];
            /** Advanced */
            advanced: string[];
        };
        /** PhaseBody */
        PhaseBody: {
            /**
             * Tolerance Deg
             * @default 1
             */
            tolerance_deg: number;
            /**
             * Max Attempts
             * @default 5
             */
            max_attempts: number;
            /**
             * Settle Time
             * @default 0.2
             */
            settle_time: number;
        };
        /** PhysicalMappingsBody */
        PhysicalMappingsBody: {
            /** Base Revision */
            base_revision: string;
            /** Mapping */
            mapping: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Constraints */
            constraints: {
                [key: string]: {
                    [key: string]: string[];
                };
            };
        };
        /** ReadbackError */
        ReadbackError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** ScopeChannelSettings */
        ScopeChannelSettings: {
            /** Number */
            number: number;
            /** Enabled */
            enabled?: boolean | null;
            /** Scale */
            scale?: number | null;
            /** Offset */
            offset?: number | null;
            /** Coupling */
            coupling?: string | null;
            /** Impedance */
            impedance?: string | null;
            /** Probe */
            probe?: number | null;
        };
        /** ScopeChannelSnapshot */
        ScopeChannelSnapshot: {
            /** Number */
            number: number;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Scale */
            scale: number;
            /** Offset */
            offset: number;
            /** Coupling */
            coupling: string;
            /** Impedance */
            impedance: string;
            /** Probe */
            probe: number;
        };
        /** ScopeDeviceSnapshot */
        ScopeDeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SDS";
            /** Idn */
            idn: string;
            /** Sampling Rate */
            sampling_rate: number;
            /** Memory Depth */
            memory_depth: string;
            /** Acquire Type */
            acquire_type: string;
            /** Timebase Scale */
            timebase_scale: number;
            /** Timebase Delay */
            timebase_delay: number;
            /** Channels */
            channels: components["schemas"]["ScopeChannelSnapshot"][];
            trigger: components["schemas"]["ScopeTriggerSnapshot"];
        };
        /** ScopeSettings */
        ScopeSettings: {
            /** Sampling Rate */
            sampling_rate?: number | null;
            /** Memory Depth */
            memory_depth?: string | null;
            /** Acquire Type */
            acquire_type?: string | null;
            /** Acquire Type Param */
            acquire_type_param?: number | null;
            /** Timebase Scale */
            timebase_scale?: number | null;
            /** Timebase Delay */
            timebase_delay?: number | null;
            /** Channels */
            channels?: components["schemas"]["ScopeChannelSettings"][] | null;
            trigger?: components["schemas"]["ScopeTriggerSettings"] | null;
        };
        /** ScopeSettingsBody */
        ScopeSettingsBody: {
            settings: components["schemas"]["ScopeSettings"];
        };
        /** ScopeTriggerSettings */
        ScopeTriggerSettings: {
            /** Mode */
            mode?: string | null;
            /** Type */
            type?: string | null;
            /** Source */
            source?: string | null;
            /** Slope */
            slope?: string | null;
            /** Level */
            level?: number | null;
        };
        /** ScopeTriggerSnapshot */
        ScopeTriggerSnapshot: {
            /** Mode */
            mode: string;
            /** Type */
            type: string;
            /** Source */
            source: string;
            /** Slope */
            slope: string;
            /** Level */
            level: number;
        };
        /** TagAssignmentBody */
        TagAssignmentBody: {
            /** Tag Id */
            tag_id: string;
        };
        /** TagBody */
        TagBody: {
            /** Label */
            label: string;
        };
        /** TecDeviceSnapshot */
        TecDeviceSnapshot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Resource */
            resource: string;
            /** Short Resource */
            short_resource: string;
            /** Options */
            options?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TEC103";
            /** Channel */
            channel: number;
            /** Target Temperature C */
            target_temperature_c: number;
            /** Actual Temperature C */
            actual_temperature_c: number | null;
            /** Enabled */
            enabled: boolean;
            /** Output Mode */
            output_mode: number;
            /** Resistance Kohm */
            resistance_kohm: number;
            /** Min Temperature C */
            min_temperature_c: number;
            /** Max Temperature C */
            max_temperature_c: number;
        };
        /** TecSettings */
        TecSettings: {
            /** Target Temperature C */
            target_temperature_c: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummary"][];
                };
            };
        };
    };
    control_targets_api_control_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetCatalog"];
                };
            };
        };
    };
    refresh_control_target_api_control_targets__mapping_key__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRevisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_all_control_targets_api_control_targets_refresh_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRevisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetBulkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_generator_api_control_targets__mapping_key__generator_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlGeneratorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_current_source_api_control_targets__mapping_key__current_source_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCurrentSourceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_laser_api_control_targets__mapping_key__laser_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlLaserBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_emission_api_control_targets__mapping_key__emission_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlEmissionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_scope_api_control_targets__mapping_key__scope_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlScopeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_control_tec_api_control_targets__mapping_key__tec_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlTecBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_library_api_device_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_device_library_api_device_library_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceLibraryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_device_library_api_device_library_discover_visa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    physical_mappings_api_physical_mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_physical_mappings_api_physical_mappings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhysicalMappingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_device_api_devices__device_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_devices__device_id__channels__channel__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                channel: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratorChannelSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scope_api_devices__device_id__scope_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_current_source_api_devices__device_id__current_source_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrentSourceSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_laser_api_devices__device_id__laser_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaserSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_laser_emission_api_devices__device_id__emission_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaserEmissionSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorDeviceSnapshot"] | components["schemas"]["ScopeDeviceSnapshot"] | components["schemas"]["CurrentSourceDeviceSnapshot"] | components["schemas"]["Keithley6221DeviceSnapshot"] | components["schemas"]["LaserDeviceSnapshot"] | components["schemas"]["TecDeviceSnapshot"] | components["schemas"]["Hf2DeviceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_clocks_api_clocks_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    phase_calibration_api_tools_demod0_phase_calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhaseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keithley_waveform_convert_api_tools_keithley_waveform_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeithleyWaveformConvertBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_tags_api_experiment_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_experiment_tag_api_experiment_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_tag_api_experiment_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_assignment_api_experiments__experiment_id__tag_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagAssignmentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_description_api_experiments__experiment_id__description_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentDescriptionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_metadata_api_experiments__experiment_id__metadata_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentMetadataBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_schema_api_experiments__experiment_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_experiment_defaults_api_experiments__experiment_id__defaults_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentDefaultsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_preflight_api_experiments__experiment_id__preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_derive_api_experiments__experiment_id__derive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_run_api_experiments__experiment_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                experiment_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_run_api_runs__run_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_runs__experiment_id___run_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frontend__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
