"""信号发生器驱动的公共接口与能力描述。"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable


@dataclass(frozen=True, slots=True)
class SignalGeneratorCapabilities:
    min_arb_points: int
    max_arb_points: int
    supports_infinite_burst: bool = True
    channels: tuple[int, ...] = (1, 2)


@runtime_checkable
class SignalGeneratorProtocol(Protocol):
    resource_string: str
    channel: int

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def setup_sine(self, freq: float, amplitude: float, **kwargs: Any) -> None: ...
    def setup_square(self, freq: float, amplitude: float, **kwargs: Any) -> None: ...
    def setup_ramp(self, freq: float, amplitude: float, **kwargs: Any) -> None: ...
    def setup_pulse(self, freq: float, amplitude: float, **kwargs: Any) -> None: ...
    def setup_noise(self, amplitude: float, **kwargs: Any) -> None: ...
    def setup_dc(self, voltage: float, **kwargs: Any) -> None: ...
    def setup_arbitrary(self, values: Any, **kwargs: Any) -> None: ...
    def set_output(self, state: bool, channel: int | None = None) -> None: ...
    def get_output(self, channel: int | None = None) -> bool: ...
    def set_phase_adjust(self, phase: float, channel: int | None = None) -> None: ...
    def get_phase_adjust(self, channel: int | None = None) -> float: ...
    def phase_init(self, channel: int | None = None) -> None: ...
    def set_mod_type(self, mod_type: str, channel: int | None = None) -> None: ...
    def set_mod_state(self, state: bool, channel: int | None = None) -> None: ...
    def set_burst_state(self, state: bool, channel: int | None = None) -> None: ...
    def set_burst_mode(self, mode: str, channel: int | None = None) -> None: ...
    def set_burst_ncycles(self, cycles: int | str, channel: int | None = None) -> None: ...
    def set_ref_clock_source(self, source: str) -> None: ...
    def get_ref_clock_source(self) -> str: ...
    def send_arbitrary_waveform(self, values: Any, channel: int | None = None) -> None: ...
